version: '3'

services:
  postgresql:
    image: bitnami/postgresql
    ports:
    - 5432:5432
    environment:
    - POSTGRESQL_USERNAME=docker
    - POSTGRESQL_PASSWORD=docker
    - POSTGRESQL_DATABASE=find-a-friend
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=my-password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16