@baseUrl = http://localhost:3333

@authToken = {{authenticate.response.body.token}}

###
# @name authenticate
POST {{baseUrl}}/orgs/auth
Content-Type: application/json

{
    "email": "jonas@email.com",
    "password": "Patr4318*"
}

###
# @name org-profile
GET {{baseUrl}}/orgs/me
Content-Type: application/json
Authorization: Bearer {{authToken}}

###
# @name register-organizations
POST {{baseUrl}}/orgs
Content-Type: application/json

{
   "responsibleName": "Jonas",
    "email": "jonas@email.com",
    "password": "Patr4318*",
    "name": "Doguinhos do amor",
    "description": "adotamos doguinhos para vc adotar companheiros de 4 patas",
    "cellNumber": "11 984985656",
    "address": "Rua Arthur Rubens del Cid",
    "addressNumber": "101",
    "addressComplement": "casa",
    "city": "São Caetano do Sul",
    "state": "São Paulo",
    "zipCode": "09520250"
}

###
# @name get-organizations-locations

POST {{baseUrl}}/orgs/locations
