export const organizationSeed = [
  {
    id: '0846dec1-6728-41c8-9e8f-c1b577604f16',
    responsible_name: 'João Silva',
    email: 'joao@email.com',
    name: 'Amigos dos Pets',
    description: 'Uma organização dedicada à adoção de pets.',
    cell_number: '987654321',
    address: 'Rua dos Animais Felizes',
    address_number: '456',
    city: 'Cidade dos Bichinhos',
    state: 'Estado Petland',
    zip_code: '54321-876',
    address_complement: 'Próximo ao Parque dos Cãezinhos',
    password: 'senha_amigos123',
  },
  {
    id: '373612f0-f8f2-434c-b38d-41c9ffba8543',
    responsible_name: 'Maria Oliveira',
    email: 'maria@email.com',
    name: 'Cães e Gatos para Sempre',
    description: 'Resgatando e cuidando de cães e gatos abandonados.',
    cell_number: '123456789',
    address: 'Avenida dos Anjos Peludos',
    address_number: '789',
    city: 'Vila Animal',
    state: 'Estado dos Peludos',
    zip_code: '98765-432',
    password: 'senha_forever456',
  },
  {
    id: 'b97a1d4b-5907-449f-bb14-3c2a9f39efcf',
    responsible_name: 'Carlos Rodrigues',
    email: 'carlos@email.com',
    name: 'Patas Solidárias',
    description: 'Ajudando animais necessitados há mais de uma década.',
    cell_number: '555444333',
    address: 'Travessa dos Amigos Fieis',
    address_number: '321',
    city: 'Cidade dos Bons Bichos',
    state: 'Estado da Compaixão',
    zip_code: '12345-678',
    password: 'senha_solidarias789',
  },
  {
    id: 'd0334ae9-98dd-4dd5-8e7e-41924e55d403',
    responsible_name: 'Ana Santos',
    email: 'ana@email.com',
    name: 'Protetores de Patinhas',
    description:
      'Comprometidos com a proteção e bem-estar de patinhas indefesas.',
    cell_number: '987123456',
    address: 'Rua das Patas Protetoras',
    address_number: '567',
    city: 'Vila dos Protetores',
    state: 'Estado da Solidariedade',
    zip_code: '87654-321',
    password: 'senha_patinhas432',
  },
  {
    id: 'd083442f-9234-4511-978b-45d9d38efe2f',
    responsible_name: 'Fernanda Lima',
    email: 'fernanda@email.com',
    name: 'Adoção com Amor',
    description:
      'Unindo corações humanos e patinhas carentes através da adoção responsável.',
    cell_number: '321987654',
    address: 'Alameda do Amor Animal',
    address_number: '987',
    city: 'Cidade Amorosa',
    state: 'Estado da Empatia',
    zip_code: '23456-789',
    password: 'senha_amorosa567',
  },
  {
    id: 'd3e3a627-7c96-48ba-bda7-6859c78367db',
    responsible_name: 'Ricardo Souza',
    email: 'ricardo@email.com',
    name: 'Resgate Animal',
    description:
      'Resgatando animais em situações de risco e proporcionando um lar seguro.',
    cell_number: '654789321',
    address: 'Avenida do Resgate',
    address_number: '654',
    city: 'Vila Segura',
    state: 'Estado Protetor',
    zip_code: '56789-012',
    password: 'senha_resgate890',
  },
  {
    id: 'fa6db70f-f256-49f4-946f-da5fcc2c777a',
    responsible_name: 'Patrícia Costa',
    email: 'patricia@email.com',
    name: 'Companheiros Fieis',
    description:
      'Dedicados a encontrar lares amorosos para animais de estimação abandonados.',
    cell_number: '789456123',
    address: 'Rua dos Companheiros',
    address_number: '345',
    city: 'Cidade dos Amigos Peludos',
    state: 'Estado Companheiro',
    zip_code: '90123-456',
    password: 'senha_fieis234',
  },
  {
    id: '818cbdf8-cd8a-4ce2-bf55-bd7f343579d6',
    responsible_name: 'Gustavo Pereira',
    email: 'gustavo@email.com',
    name: 'Amor Pet',
    description:
      'Promovendo a adoção responsável e o amor incondicional por animais de estimação.',
    cell_number: '456321789',
    address: 'Praça do Amor Pet',
    address_number: '123',
    city: 'Vila Petinho',
    state: 'Estado do Afeto',
    zip_code: '34567-890',
    password: 'senha_amorpet567',
  },
  {
    id: 'ed22d228-cb52-4d17-8990-d3a13f01fe18',
    responsible_name: 'Lúcia Mendes',
    email: 'lucia@email.com',
    name: 'Anjos Peludos',
    description:
      'Trabalhando como anjos para resgatar e cuidar de animais necessitados.',
    cell_number: '987654987',
    address: 'Travessa dos Anjos',
    address_number: '789',
    city: 'Cidade dos Anjinhos',
    state: 'Estado dos Cuidados',
    zip_code: '87654-321',
    password: 'senha_anjospeludos678',
  },
  {
    id: '36e1a0fd-efc1-4ae3-a815-37450f40f283',
    responsible_name: 'Anderson Silva',
    email: 'anderson@email.com',
    name: 'Família Pet',
    description:
      'Buscando lares amorosos para animais abandonados e promovendo a responsabilidade pet.',
    cell_number: '123987456',
    address: 'Alameda da Família Pet',
    address_number: '567',
    city: 'Vila dos Amigos Felpudos',
    state: 'Estado dos Pets',
    zip_code: '43210-987',
    password: 'senha_familiapet789',
  },
]
