import { randomUUID } from 'node:crypto'

export const petSeed = [
  {
    id: randomUUID(),
    name: 'Bella',
    about: 'Bella é uma cadelinha muito amigável e brincalhona.',
    age: '2 anos',
    size: 'Médio',
    level_of_independence: 3,
    photos: [
      'https://example.com/bella1.jpg',
      'https://example.com/bella2.jpg',
      'https://example.com/bella3.jpg',
    ],
    environment: 'Indoor',
    requirements_for_adoption: ['Pátio cercado', 'Passeios diários'],
    status: 'Disponível',
    city: 'Cidade dos Animais',
  },
  {
    id: randomUUID(),
    name: 'Max',
    about: 'Max é um gatinho curioso e adora brincar com bolinhas de pelo.',
    age: '1 ano',
    size: 'Pequeno',
    level_of_independence: 2,
    photos: [
      'https://example.com/max1.jpg',
      'https://example.com/max2.jpg',
      'https://example.com/max3.jpg',
    ],
    environment: 'Indoor',
    requirements_for_adoption: ['Arranhador', 'Brinquedos interativos'],
    status: 'Disponível',
    city: 'Cidade dos Gatos',
  },
  {
    id: randomUUID(),
    name: 'Luna',
    about: 'Luna é uma gatinha tranquila e adora cochilos ao sol.',
    age: '3 anos',
    size: 'Pequeno',
    level_of_independence: 4,
    photos: [
      'https://example.com/luna1.jpg',
      'https://example.com/luna2.jpg',
      'https://example.com/luna3.jpg',
    ],
    environment: 'Indoor',
    requirements_for_adoption: ['Janelas amplas', 'Cama confortável'],
    status: 'Disponível',
    city: 'Cidade dos Gatos',
  },
  {
    id: randomUUID(),
    name: 'Thor',
    about: 'Thor é um cachorro energético e adora correr no parque.',
    age: '1 ano e meio',
    size: 'Grande',
    level_of_independence: 2,
    photos: [
      'https://example.com/thor1.jpg',
      'https://example.com/thor2.jpg',
      'https://example.com/thor3.jpg',
    ],
    environment: 'Outdoor',
    requirements_for_adoption: [
      'Área externa espaçosa',
      'Atividades físicas regulares',
    ],
    status: 'Disponível',
    city: 'Cidade dos Cães',
  },
  {
    id: randomUUID(),
    name: 'Mia',
    about: 'Mia é uma gatinha curiosa e adora explorar novos lugares.',
    age: '2 anos',
    size: 'Pequeno',
    level_of_independence: 3,
    photos: [
      'https://example.com/mia1.jpg',
      'https://example.com/mia2.jpg',
      'https://example.com/mia3.jpg',
    ],
    environment: 'Indoor',
    requirements_for_adoption: [
      'Brinquedos interativos',
      'Esconderijos confortáveis',
    ],
    status: 'Disponível',
    city: 'Cidade dos Gatos',
  },
  {
    id: randomUUID(),
    name: 'Charlie',
    about: 'Charlie é um cachorro adorável que gosta de receber carinho.',
    age: '3 anos',
    size: 'Médio',
    level_of_independence: 2,
    photos: [
      'https://example.com/charlie1.jpg',
      'https://example.com/charlie2.jpg',
      'https://example.com/charlie3.jpg',
    ],
    environment: 'Indoor',
    requirements_for_adoption: ['Tempo de qualidade', 'Passeios diários'],
    status: 'Disponível',
    city: 'Cidade dos Cães',
  },
  {
    id: randomUUID(),
    name: 'Lola',
    about:
      'Lola é uma cadelinha brincalhona que adora interagir com outros animais.',
    age: '2 anos',
    size: 'Pequeno',
    level_of_independence: 3,
    photos: [
      'https://example.com/lola1.jpg',
      'https://example.com/lola2.jpg',
      'https://example.com/lola3.jpg',
    ],
    environment: 'Outdoor',
    requirements_for_adoption: [
      'Companhia de outros animais',
      'Espaço para correr',
    ],
    status: 'Disponível',
    city: 'Cidade dos Animais',
  },
  {
    id: randomUUID(),
    name: 'Oliver',
    about: 'Oliver é um gatinho curioso e adora brincar com bolinhas de pelo.',
    age: '1 ano',
    size: 'Pequeno',
    level_of_independence: 4,
    photos: [
      'https://example.com/oliver1.jpg',
      'https://example.com/oliver2.jpg',
      'https://example.com/oliver3.jpg',
    ],
    environment: 'Indoor',
    requirements_for_adoption: ['Brinquedos variados', 'Arranhador'],
    status: 'Disponível',
    city: 'Cidade dos Gatos',
  },
  {
    id: randomUUID(),
    name: 'Sophie',
    about: 'Sophie é uma cadelinha adorável que gosta de passeios tranquilos.',
    age: '4 anos',
    size: 'Médio',
    level_of_independence: 2,
    photos: [
      'https://example.com/sophie1.jpg',
      'https://example.com/sophie2.jpg',
      'https://example.com/sophie3.jpg',
    ],
    environment: 'Outdoor',
    requirements_for_adoption: ['Passeios diários', 'Área externa segura'],
    status: 'Disponível',
    city: 'Cidade dos Cães',
  },
  {
    id: randomUUID(),
    name: 'Leo',
    about: 'Leo é um gatinho calmo que gosta de cochilar ao sol.',
    age: '3 anos',
    size: 'Pequeno',
    level_of_independence: 3,
    photos: [
      'https://example.com/leo1.jpg',
      'https://example.com/leo2.jpg',
      'https://example.com/leo3.jpg',
    ],
    environment: 'Indoor',
    requirements_for_adoption: ['Janelas amplas', 'Cama confortável'],
    status: 'Disponível',
    city: 'Cidade dos Gatos',
  },
]
